// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fnTimesTwo
NumericVector fnTimesTwo(NumericVector x);
RcppExport SEXP _diseaseRiskPredictor_fnTimesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fnTimesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// na_matrix
Rcpp::NumericMatrix na_matrix(const int nrow, const int ncol);
RcppExport SEXP _diseaseRiskPredictor_na_matrix(SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< const int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(na_matrix(nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// scalarN
double scalarN(const double m, const double s);
RcppExport SEXP _diseaseRiskPredictor_scalarN(SEXP mSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type m(mSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(scalarN(m, s));
    return rcpp_result_gen;
END_RCPP
}
// scalarU
double scalarU(const double m, const double s);
RcppExport SEXP _diseaseRiskPredictor_scalarU(SEXP mSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type m(mSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(scalarU(m, s));
    return rcpp_result_gen;
END_RCPP
}
// cppFnGibbsSampler
Rcpp::NumericMatrix cppFnGibbsSampler(Rcpp::DataFrame dfPed, const Rcpp::NumericMatrix mPriorMean, const Rcpp::List lmRegCoeff, const Rcpp::NumericVector vPostStdDev, const Rcpp::NumericVector vDrawInit, const int nofBurnIn, const int nofIter, const int nofVariables, const Rcpp::CharacterVector vsVariables, const Rcpp::CharacterVector vPerson, const Rcpp::LogicalVector vbxLia, const int iMaxAttempts);
RcppExport SEXP _diseaseRiskPredictor_cppFnGibbsSampler(SEXP dfPedSEXP, SEXP mPriorMeanSEXP, SEXP lmRegCoeffSEXP, SEXP vPostStdDevSEXP, SEXP vDrawInitSEXP, SEXP nofBurnInSEXP, SEXP nofIterSEXP, SEXP nofVariablesSEXP, SEXP vsVariablesSEXP, SEXP vPersonSEXP, SEXP vbxLiaSEXP, SEXP iMaxAttemptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dfPed(dfPedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type mPriorMean(mPriorMeanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type lmRegCoeff(lmRegCoeffSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type vPostStdDev(vPostStdDevSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type vDrawInit(vDrawInitSEXP);
    Rcpp::traits::input_parameter< const int >::type nofBurnIn(nofBurnInSEXP);
    Rcpp::traits::input_parameter< const int >::type nofIter(nofIterSEXP);
    Rcpp::traits::input_parameter< const int >::type nofVariables(nofVariablesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector >::type vsVariables(vsVariablesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector >::type vPerson(vPersonSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector >::type vbxLia(vbxLiaSEXP);
    Rcpp::traits::input_parameter< const int >::type iMaxAttempts(iMaxAttemptsSEXP);
    rcpp_result_gen = Rcpp::wrap(cppFnGibbsSampler(dfPed, mPriorMean, lmRegCoeff, vPostStdDev, vDrawInit, nofBurnIn, nofIter, nofVariables, vsVariables, vPerson, vbxLia, iMaxAttempts));
    return rcpp_result_gen;
END_RCPP
}
// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP _diseaseRiskPredictor_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_diseaseRiskPredictor_fnTimesTwo", (DL_FUNC) &_diseaseRiskPredictor_fnTimesTwo, 1},
    {"_diseaseRiskPredictor_na_matrix", (DL_FUNC) &_diseaseRiskPredictor_na_matrix, 2},
    {"_diseaseRiskPredictor_scalarN", (DL_FUNC) &_diseaseRiskPredictor_scalarN, 2},
    {"_diseaseRiskPredictor_scalarU", (DL_FUNC) &_diseaseRiskPredictor_scalarU, 2},
    {"_diseaseRiskPredictor_cppFnGibbsSampler", (DL_FUNC) &_diseaseRiskPredictor_cppFnGibbsSampler, 12},
    {"_diseaseRiskPredictor_timesTwo", (DL_FUNC) &_diseaseRiskPredictor_timesTwo, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_diseaseRiskPredictor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
