# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fnTimesTwo <- function(x) {
    .Call(`_diseaseRiskPredictor_fnTimesTwo`, x)
}

na_matrix <- function(nrow, ncol) {
    .Call(`_diseaseRiskPredictor_na_matrix`, nrow, ncol)
}

scalarN <- function(m, s) {
    .Call(`_diseaseRiskPredictor_scalarN`, m, s)
}

scalarU <- function(m, s) {
    .Call(`_diseaseRiskPredictor_scalarU`, m, s)
}

cppFnGibbsSampler <- function(dfPed, mPriorMean, lmRegCoeff, vPostStdDev, vDrawInit, nofBurnIn, nofIter, nofVariables, vsVariables, vPerson, vbxLia, iMaxAttempts = 500000L) {
    .Call(`_diseaseRiskPredictor_cppFnGibbsSampler`, dfPed, mPriorMean, lmRegCoeff, vPostStdDev, vDrawInit, nofBurnIn, nofIter, nofVariables, vsVariables, vPerson, vbxLia, iMaxAttempts)
}

timesTwo <- function(x) {
    .Call(`_diseaseRiskPredictor_timesTwo`, x)
}

